import * as THREE from 'three';
export const CONFIG={title:'Ashfall Protocol',version:'0.1.0',world:{size:48,height:18,block:2},player:{speed:8,sprint:13,jump:10,reach:7,gravity:26},combat:{attackCooldown:.35,damage:18,projectileSpeed:28},saveKey:'ashfall_protocol_save_v1'};
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const lerp=(a,b,t)=>a+(b-a)*t;
export const rand=(a=0,b=1)=>a+Math.random()*(b-a);
export const choose=a=>a[Math.floor(Math.random()*a.length)];
export class EventBus{constructor(){this.map=new Map()}on(k,f){if(!this.map.has(k))this.map.set(k,new Set());this.map.get(k).add(f);return()=>this.off(k,f)}off(k,f){this.map.get(k)?.delete(f)}emit(k,p){this.map.get(k)?.forEach(f=>f(p))}}
export class InputManager{constructor(){this.keys=new Set();this.mouse=new THREE.Vector2();this.buttons=new Set();this.locked=false;window.addEventListener('keydown',e=>{this.keys.add(e.code);if(e.code==='KeyP')this.bus?.emit('pause')});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('mousedown',e=>this.buttons.add(e.button));window.addEventListener('mouseup',e=>this.buttons.delete(e.button));window.addEventListener('mousemove',e=>{this.mouse.x=e.movementX;this.mouse.y=e.movementY});window.addEventListener('blur',()=>this.keys.clear());}bindBus(b){this.bus=b}down(k){return this.keys.has(k)}pressedMouse(b=0){return this.buttons.has(b)}}
export const GameState=Object.freeze({BOOT:'boot',MENU:'menu',PLAYING:'playing',PAUSED:'paused',GAME_OVER:'game_over',VICTORY:'victory'});
export class StateMachine{constructor(bus){this.bus=bus;this.current=GameState.BOOT}change(s){if(this.current===s)return;const old=this.current;this.current=s;this.bus.emit('state:changed',{old,next:s})}is(s){return this.current===s}}
export class SaveSystem{constructor(){this.key=CONFIG.saveKey}defaultData(){return {version:1,gold:0,level:1,kills:0,achievements:[],settings:{sensitivity:1,music:true,sfx:true},world:{seed:2026},player:{}}}load(){try{const raw=localStorage.getItem(this.key);if(!raw)return this.defaultData();return Object.assign(this.defaultData(),JSON.parse(raw))}catch(e){console.warn('Save load failed',e);return this.defaultData()}}save(data){try{localStorage.setItem(this.key,JSON.stringify(data));return true}catch(e){console.error('Save failed',e);return false}}}
export class GameClock{constructor(){this.last=performance.now();this.delta=0;this.time=0}tick(){const n=performance.now();this.delta=Math.min(.05,(n-this.last)/1000);this.last=n;this.time+=this.delta;return this.delta}}
export class Game{constructor({THREE,canvas}){this.THREE=THREE;this.canvas=canvas;this.bus=new EventBus();this.input=new InputManager();this.input.bindBus(this.bus);this.state=new StateMachine(this.bus);this.save=new SaveSystem();this.clock=new GameClock();this.profile=this.save.load();this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x86b6d9);this.camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.05,500);this.camera.position.set(0,8,12);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.light=new THREE.HemisphereLight(0xbad9ff,0x253020,1.6);this.scene.add(this.light);this.sun=new THREE.DirectionalLight(0xffffff,2.2);this.sun.position.set(20,35,15);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);this.scene.add(this.sun);window.addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});this.bus.on('pause',()=>this.togglePause?.())}
loop(){requestAnimationFrame(()=>this.loop());const dt=this.clock.tick();if(this.state.is(GameState.PLAYING))this.update(dt);this.renderer.render(this.scene,this.camera)}
update(){}}
