import * as THREE from 'three';
import {CONFIG,clamp,rand,choose} from './core.js';
class Enemy{constructor(T,scene,bus,world,player,type='scavenger',pos=new T.Vector3()){this.T=T;this.scene=scene;this.bus=bus;this.world=world;this.player=player;this.type=type;this.position=pos.clone();this.max=type==='brute'?90:type==='shooter'?55:45;this.health=this.max;this.speed=type==='charger'?7:type==='brute'?2.8:4.2;this.cool=rand(.2,1);this.dead=false;this.mesh=this.makeMesh()}
makeMesh(){const color=this.type==='brute'?0x9b3d3d:this.type==='shooter'?0x8a6bb5:this.type==='charger'?0xc47c2b:0x6b6f78;const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1.4,1.8,1.2),new THREE.MeshLambertMaterial({color}));body.position.y=.9;body.castShadow=true;g.add(body);const eye=new THREE.Mesh(new THREE.BoxGeometry(.5,.3,.1),new THREE.MeshBasicMaterial({color:0xff3322}));eye.position.set(0,1.25,-.62);g.add(eye);g.position.copy(this.position);this.scene.add(g);return g}
update(dt){if(this.dead)return;this.cool=Math.max(0,this.cool-dt);const to=this.player.position.clone().sub(this.position);const dist=to.length();if(dist<18){to.y=0;to.normalize();let speed=this.speed;if(this.type==='shooter'&&dist<8)to.multiplyScalar(-1);this.position.addScaledVector(to,speed*dt);this.position.y=this.world.heightAt(this.position.x,this.position.z);this.mesh.position.copy(this.position);this.mesh.lookAt(this.player.position.x,this.position.y+1,this.player.position.z);if(dist<1.8&&this.cool<=0){this.cool=this.type==='charger'?1.3:1;this.player.health.damage(this.type==='brute'?18:10,this.type)}}}
damage(n){if(this.dead)return;this.health=clamp(this.health-n,0,this.max);this.bus.emit('enemy:damaged',{enemy:this,amount:n});if(this.health<=0)this.die()}
die(){if(this.dead)return;this.dead=true;this.scene.remove(this.mesh);this.bus.emit('enemy:died',{enemy:this,reward:this.type==='brute'?35:this.type==='shooter'?25:15});this.player.kills++;this.player.addXP(this.type==='brute'?40:20)}}
export class EnemyDirector{constructor(T,scene,bus,world,player){this.T=T;this.scene=scene;this.bus=bus;this.world=world;this.player=player;this.enemies=[];this.spawnTimer=1;this.ray=new T.Raycaster();this.bus.on('player:attack',e=>this.attack(e));for(let i=0;i<10;i++)this.spawn(i)}
spawn(i){const a=rand(0,Math.PI*2),r=rand(10,22);const p=new this.T.Vector3(Math.cos(a)*r,0,Math.sin(a)*r);p.y=this.world.heightAt(p.x,p.z);const type=choose(['scavenger','scavenger','shooter','charger','brute']);this.enemies.push(new Enemy(this.T,this.scene,this.bus,this.world,this.player,type,p))}
update(dt){this.enemies=this.enemies.filter(e=>!e.dead);this.enemies.forEach(e=>e.update(dt));this.spawnTimer-=dt;if(this.spawnTimer<=0&&this.enemies.length<14){this.spawnTimer=2.5;this.spawn(this.enemies.length)}}
attack(e){const origin=this.player.position.clone().add(new this.T.Vector3(0,1.2,0));const dir=new this.T.Vector3(Math.sin(e.yaw),e.pitch||0,Math.cos(e.yaw)).normalize();this.ray.set(origin,dir);const targets=this.enemies.map(x=>x.mesh);const hits=this.ray.intersectObjects(targets,true);if(!hits.length)return;let obj=hits[0].object;while(obj.parent&&!targets.includes(obj))obj=obj.parent;const enemy=this.enemies.find(x=>x.mesh===obj);if(enemy&&hits[0].distance<CONFIG.player.reach*2)enemy.damage(e.damage)}}
export class Boss{constructor(T,scene,bus,player){this.T=T;this.scene=scene;this.bus=bus;this.player=player;this.health=500;this.max=500;this.phase=1;this.active=false;this.cool=3;this.mesh=this.makeMesh();this.mesh.visible=false;this.bus.on('enemy:died',()=>{if(!this.active&&this.player.kills>=15)this.activate()});this.bus.on('player:attack',e=>this.onAttack(e))}
makeMesh(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(4,5,4),new THREE.MeshLambertMaterial({color:0x492c56,emissive:0x190c20}));body.position.y=2.5;body.castShadow=true;g.add(body);return g}
activate(){this.active=true;this.mesh.visible=true;this.mesh.position.set(0,this.player.position.y, -12);this.bus.emit('boss:activated')}
onAttack(e){if(!this.active)return;const d=this.mesh.position.distanceTo(this.player.position);if(d<8)this.health=clamp(this.health-e.damage,0,this.max);if(this.health<=this.max*.5)this.phase=2;if(this.health<=0)this.defeat()}
update(dt){if(!this.active)return;this.cool-=dt;this.mesh.lookAt(this.player.position.x,this.mesh.position.y,this.player.position.z);if(this.cool<=0){this.cool=this.phase===2?1.1:1.8;const d=this.mesh.position.distanceTo(this.player.position);if(d<15)this.player.health.damage(this.phase===2?25:16,'boss');if(this.phase===2)this.mesh.scale.setScalar(1.05+Math.sin(performance.now()*.006)*.05)}}
defeat(){this.active=false;this.mesh.visible=false;this.bus.emit('boss:defeated')}}
export class LootSystem{constructor(T,scene,bus){this.T=T;this.scene=scene;this.bus=bus;this.items=[];this.bus.on('enemy:died',e=>this.drop(e.enemy.position,'xp',e.reward))}
drop(pos,type,value){const g=new this.T.Mesh(new this.T.BoxGeometry(.45,.45,.45),new this.T.MeshLambertMaterial({color:type==='coin'?0xffd447:0x6ce0ff,emissive:type==='coin'?0x442b00:0x063344}));g.position.copy(pos).y+=.8;g.userData={type,value};this.scene.add(g);this.items.push(g)}
update(dt,player){for(let i=this.items.length-1;i>=0;i--){const it=this.items[i];it.rotation.y+=dt*3;const d=it.position.distanceTo(player.position);if(d<5){it.position.lerp(player.position,.08);if(d<1){const {type,value}=it.userData;if(type==='coin')player.addGold(value);else player.addXP(value);this.scene.remove(it);this.items.splice(i,1)}}}}
}
