import * as THREE from 'three';
import {CONFIG,clamp,lerp} from './core.js';
export const CameraMode=Object.freeze({FIRST:0,THIRD:1,TOP:2});
class Health{constructor(max,bus){this.max=max;this.value=max;this.bus=bus;this.invuln=0}update(dt){this.invuln=Math.max(0,this.invuln-dt)}damage(n,source){if(this.invuln>0)return false;this.value=clamp(this.value-n,0,this.max);this.invuln=.25;this.bus.emit('player:damaged',{amount:n,source,health:this.value});if(this.value<=0)this.bus.emit('player:died');return true}heal(n){this.value=clamp(this.value+n,0,this.max);this.bus.emit('player:healed',{amount:n,health:this.value})}}
export class Player{constructor(T,scene,world,bus,input,profile){this.T=T;this.scene=scene;this.world=world;this.bus=bus;this.input=input;this.profile=profile;this.position=world.spawn.clone();this.velocity=new THREE.Vector3();this.yaw=0;this.pitch=0;this.mode=CameraMode.FIRST;this.health=new Health(100,bus);this.stamina=100;this.xp=0;this.level=1;this.gold=0;this.kills=0;this.attackTimer=0;this.jumpReady=true;this.mesh=this.makeMesh();this.cameraPivot=new THREE.Object3D();this.cameraPivot.position.copy(this.position);scene.add(this.cameraPivot);this.bus.on('enemy:hit',e=>{});window.addEventListener('keydown',e=>{if(e.code==='Digit1')this.mode=CameraMode.FIRST;if(e.code==='Digit2')this.mode=CameraMode.THIRD;if(e.code==='Digit3')this.mode=CameraMode.TOP})}
makeMesh(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1.2,1.8,1),new THREE.MeshLambertMaterial({color:0x344c65}));body.position.y=.9;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.BoxGeometry(.9,.9,.9),new THREE.MeshLambertMaterial({color:0xc18b6d}));head.position.y=2;head.castShadow=true;g.add(head);g.position.copy(this.position);this.scene.add(g);return g}
update(dt){this.health.update(dt);this.attackTimer=Math.max(0,this.attackTimer-dt);this.handleLook();this.handleMovement(dt);this.handleCombat();this.mesh.position.copy(this.position);this.mesh.visible=this.mode!==CameraMode.FIRST}
handleLook(){if(!document.pointerLockElement)return;this.yaw-=this.input.mouse.x*.002*this.profile.settings.sensitivity;this.pitch=clamp(this.pitch-this.input.mouse.y*.002*this.profile.settings.sensitivity,-1.35,1.35);this.input.mouse.set(0,0)}
handleMovement(dt){const forward=new THREE.Vector3(Math.sin(this.yaw),0,Math.cos(this.yaw));const right=new THREE.Vector3(forward.z,0,-forward.x);const wish=new THREE.Vector3();if(this.input.down('KeyW'))wish.add(forward.clone().multiplyScalar(-1));if(this.input.down('KeyS'))wish.add(forward);if(this.input.down('KeyA'))wish.sub(right);if(this.input.down('KeyD'))wish.add(right);if(wish.lengthSq()>0)wish.normalize();const sprint=this.input.down('ShiftLeft')&&this.stamina>0;const speed=sprint?CONFIG.player.sprint:CONFIG.player.speed;if(sprint&&wish.lengthSq())this.stamina=clamp(this.stamina-dt*18,0,100);else this.stamina=clamp(this.stamina+dt*12,0,100);const target=wish.multiplyScalar(speed);this.velocity.x=lerp(this.velocity.x,target.x,Math.min(1,dt*12));this.velocity.z=lerp(this.velocity.z,target.z,Math.min(1,dt*12));const ground=this.world.heightAt(this.position.x,this.position.z);if(this.position.y<=ground+.05){this.position.y=ground;this.velocity.y=0;this.jumpReady=true;if(this.input.down('Space')&&this.jumpReady){this.velocity.y=CONFIG.player.jump;this.jumpReady=false}}else this.velocity.y-=CONFIG.player.gravity*dt;const next=this.position.clone().addScaledVector(this.velocity,dt);const ng=this.world.heightAt(next.x,next.z);if(ng>0&&next.y>=ng-.15){this.position.x=next.x;this.position.z=next.z;this.position.y=Math.max(next.y,ng)}else{this.velocity.x*=.2;this.velocity.z*=.2}}
handleCombat(){if(this.input.pressedMouse(0)&&this.attackTimer<=0){this.attackTimer=CONFIG.combat.attackCooldown;this.bus.emit('player:attack',{position:this.position.clone(),yaw:this.yaw,pitch:this.pitch,damage:CONFIG.combat.damage})}}
updateCamera(camera){const target=this.position.clone().add(new THREE.Vector3(0,1.5,0));this.cameraPivot.position.lerp(target,.2);if(this.mode===CameraMode.FIRST){camera.position.copy(target);camera.rotation.order='YXZ';camera.rotation.y=this.yaw;camera.rotation.x=this.pitch}else if(this.mode===CameraMode.THIRD){const offset=new THREE.Vector3(0,2.5,6).applyEuler(new THREE.Euler(this.pitch,this.yaw,0,'YXZ'));camera.position.lerp(target.clone().add(offset),.15);camera.lookAt(target)}else{camera.position.lerp(new THREE.Vector3(this.position.x,24,this.position.z+8),.15);camera.lookAt(this.position)}}
addXP(n){this.xp+=n;while(this.xp>=this.level*100){this.xp-=this.level*100;this.level++;this.health.max+=8;this.health.heal(this.health.max);this.bus.emit('player:levelup',{level:this.level})}}
addGold(n){this.gold+=n;this.bus.emit('player:gold',{gold:this.gold})}
serialize(){return{position:this.position.toArray(),health:this.health.value,maxHealth:this.health.max,stamina:this.stamina,xp:this.xp,level:this.level,gold:this.gold,kills:this.kills,mode:this.mode,yaw:this.yaw,pitch:this.pitch}}
deserialize(d){if(!d)return;this.position.fromArray(d.position||this.position.toArray());this.health.max=d.maxHealth||100;this.health.value=d.health??this.health.max;this.stamina=d.stamina??100;this.xp=d.xp||0;this.level=d.level||1;this.gold=d.gold||0;this.kills=d.kills||0;this.mode=d.mode??CameraMode.FIRST;this.yaw=d.yaw||0;this.pitch=d.pitch||0}
}
export class InteractionController{constructor(T,game,player,world,bus){this.T=T;this.game=game;this.player=player;this.world=world;this.bus=bus;this.ray=new T.Raycaster();this.center=new T.Vector2(0,0);this.selected=null;window.addEventListener('click',()=>{if(game.state.is('playing')&&document.body.requestPointerLock)document.body.requestPointerLock()})}
update(){this.ray.setFromCamera(this.center,this.game.camera);const hits=this.ray.intersectObjects(this.world.raycastMeshes(),false);this.selected=hits.find(h=>h.distance<=CONFIG.player.reach)||null;}}
