import {GameState} from './core.js';
export function installStyle(){const s=document.createElement('style');s.textContent=`*{box-sizing:border-box}body{margin:0;overflow:hidden;background:#081016;font-family:Inter,Arial,sans-serif;color:#fff}#ui{position:fixed;inset:0;pointer-events:none}.panel{pointer-events:auto;position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;background:linear-gradient(180deg,rgba(3,8,12,.9),rgba(3,8,12,.72));backdrop-filter:blur(5px)}.panel h1{font-size:54px;margin:0 0 8px;text-shadow:0 4px 20px #000}.panel p{opacity:.8}.btn{pointer-events:auto;border:1px solid #5c7685;background:#172832;color:#fff;padding:12px 22px;margin:6px;border-radius:8px;font-size:16px;cursor:pointer}.btn:hover{background:#24404e}.hud{position:absolute;left:18px;top:18px;min-width:250px;background:rgba(0,0,0,.45);padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:10px}.bar{height:10px;background:#20262b;border-radius:6px;overflow:hidden;margin-top:5px}.fill{height:100%;width:100%;background:#56d47a}.xp .fill{background:#6cb6ff}.cross{position:absolute;left:50%;top:50%;width:18px;height:18px;transform:translate(-50%,-50%)}.cross:before,.cross:after{content:'';position:absolute;background:#fff}.cross:before{width:18px;height:2px;top:8px}.cross:after{width:2px;height:18px;left:8px}.toast{position:absolute;left:50%;bottom:60px;transform:translateX(-50%);padding:10px 18px;background:rgba(0,0,0,.7);border-radius:8px}`;document.head.appendChild(s)}
export class UIManager{constructor(bus,game){this.bus=bus;this.game=game;this.root=document.getElementById('ui');this.hud=null;this.toastNode=null;this.makeMenu();this.makeHUD();bus.on('state:changed',e=>this.renderState(e.next));bus.on('player:levelup',e=>this.toast('Seviye '+e.level+'!'));bus.on('boss:activated',()=>this.toast('BOSS AKTİF'));bus.on('boss:defeated',()=>this.toast('Boss yenildi!'));this.renderState(GameState.MENU)}
makeMenu(){this.menu=document.createElement('div');this.menu.className='panel';this.menu.innerHTML=`<h1>ASHFALL PROTOCOL</h1><p>3D blok dünyada keşfet, savaş ve hayatta kal.</p><div><button class="btn" id="new">Yeni Oyun</button><button class="btn" id="load">Oyunu Yükle</button></div><p>WASD hareket · Space zıpla · Shift koş · Sol tık saldır · P duraklat · 1/2/3 kamera</p>`;this.root.appendChild(this.menu);this.menu.querySelector('#new').onclick=()=>this.game.startNewGame();this.menu.querySelector('#load').onclick=()=>this.game.loadGame()}
makeHUD(){this.hud=document.createElement('div');this.hud.className='hud';this.hud.innerHTML=`<b>ASHFALL</b><div>Can <span id="hp">100</span></div><div class="bar"><div class="fill" id="hpbar"></div></div><div>Enerji <span id="st">100</span></div><div class="bar"><div class="fill" id="stbar"></div></div><div>XP <span id="xp">0</span> · Seviye <span id="lv">1</span></div><div class="bar xp"><div class="fill" id="xpbar"></div></div><div>Altın: <span id="gold">0</span> · Öldürme: <span id="kills">0</span></div>`;this.root.appendChild(this.hud);this.cross=document.createElement('div');this.cross.className='cross';this.root.appendChild(this.cross)}
renderState(state){this.menu.style.display=state===GameState.MENU?'flex':'none';this.hud.style.display=state===GameState.PLAYING?'block':'none';this.cross.style.display=state===GameState.PLAYING?'block':'none';if(state===GameState.PAUSED)this.overlay('DURAKLATILDI',()=>this.game.resume());if(state===GameState.GAME_OVER)this.overlay('OYUN BİTTİ',()=>this.game.startNewGame());}
overlay(title,action){if(this.overlayNode)this.overlayNode.remove();this.overlayNode=document.createElement('div');this.overlayNode.className='panel';this.overlayNode.innerHTML=`<h1>${title}</h1><button class="btn">Devam</button><button class="btn">Ana Menü</button>`;this.root.appendChild(this.overlayNode);this.overlayNode.children[1].onclick=action;this.overlayNode.children[2].onclick=()=>{this.overlayNode.remove();this.game.toMenu()}}
update(p){if(!p||!this.hud)return;this.hud.querySelector('#hp').textContent=Math.ceil(p.health.value);this.hud.querySelector('#hpbar').style.width=(p.health.value/p.health.max*100)+'%';this.hud.querySelector('#st').textContent=Math.ceil(p.stamina);this.hud.querySelector('#stbar').style.width=p.stamina+'%';this.hud.querySelector('#xp').textContent=Math.floor(p.xp);this.hud.querySelector('#lv').textContent=p.level;this.hud.querySelector('#xpbar').style.width=(p.xp/(p.level*100)*100)+'%';this.hud.querySelector('#gold').textContent=p.gold;this.hud.querySelector('#kills').textContent=p.kills}
toast(text){if(this.toastNode)this.toastNode.remove();this.toastNode=document.createElement('div');this.toastNode.className='toast';this.toastNode.textContent=text;this.root.appendChild(this.toastNode);setTimeout(()=>this.toastNode?.remove(),1800)}}
